my_string = input('Укажите регион Вашего проживания (Например: "Московская область"):')
print('Название Вашего региона состоит из',len(my_string),'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])
